# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('scientific_name', models.CharField(max_length=64, unique=True)),
                ('common_name', models.CharField(max_length=64, unique=True)),
                ('habit', models.PositiveSmallIntegerField(choices=[(0, 'twiggy')])),
                ('form', models.PositiveSmallIntegerField(choices=[(0, 'round')])),
                ('height', models.FloatField()),
                ('spread', models.FloatField()),
                ('growth_rate', models.PositiveSmallIntegerField(choices=[(0, 'moderate')])),
                ('climate', models.PositiveSmallIntegerField(choices=[(0, 'moderate')])),
                ('water', models.PositiveSmallIntegerField(choices=[(0, 'moderate')])),
                ('can_flower', models.BooleanField()),
                ('can_fruit', models.BooleanField()),
            ],
        ),
    ]
