# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('colour', models.PositiveSmallIntegerField(choices=[(0, 'brown')])),
                ('scent', models.PositiveSmallIntegerField(choices=[(0, 'fragrant')])),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('colour', models.PositiveSmallIntegerField(choices=[(0, 'brown')])),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'capsule')])),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='flower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Flower'),
        ),
        migrations.AddField(
            model_name='plant',
            name='fruit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Fruit'),
        ),
    ]
