# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170307_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('month', models.PositiveSmallIntegerField(choices=[(0, 'January'), (1, 'February'), (2, 'March'), (3, 'April'), (4, 'May'), (5, 'June'), (6, 'July'), (7, 'August'), (8, 'Septembre'), (9, 'Octobre'), (10, 'Novembre'), (11, 'Decembre')])),
            ],
        ),
        migrations.AddField(
            model_name='flower',
            name='months',
            field=models.ManyToManyField(to='main.Month'),
        ),
        migrations.AddField(
            model_name='fruit',
            name='months',
            field=models.ManyToManyField(to='main.Month'),
        ),
    ]
