# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170307_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='months',
            field=models.ManyToManyField(null=True, to='main.Month'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='months',
            field=models.ManyToManyField(null=True, to='main.Month'),
        ),
    ]
