# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170307_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('blob', models.BinaryField(null=True)),
                ('path', models.FilePathField()),
                ('flowers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Flower')),
                ('fruits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Fruit')),
                ('plants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Plant')),
            ],
        ),
    ]
