# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False, unique=True)),
                ('exposure', models.PositiveSmallIntegerField(choices=[(0, '')])),
            ],
        ),
        migrations.CreateModel(
            name='LandscapeUse',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False, unique=True)),
                ('landscape', models.PositiveSmallIntegerField(choices=[(0, '')])),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('user_id', models.CharField(max_length=90, primary_key=True, serialize=False, unique=True)),
                ('last_operation', models.DateField()),
                ('cookie', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False, unique=True)),
                ('exposure', models.PositiveSmallIntegerField(choices=[(0, '')])),
            ],
        ),
        migrations.AlterField(
            model_name='flower',
            name='id',
            field=models.CharField(max_length=90, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='id',
            field=models.CharField(max_length=90, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.CharField(max_length=90, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='id',
            field=models.CharField(max_length=90, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='id',
            field=models.CharField(max_length=90, primary_key=True, serialize=False, unique=True),
        ),
    ]
