# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170309_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False, unique=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('ph', models.FloatField()),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '')])),
            ],
        ),
        migrations.CreateModel(
            name='PlantSpot',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False, unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_spots', to='main.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False, unique=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='main.Area')),
                ('plant_spot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='main.PlantSpot')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('creation_date', models.DateField()),
                ('update_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='flowers',
        ),
        migrations.RemoveField(
            model_name='image',
            name='fruits',
        ),
        migrations.RemoveField(
            model_name='image',
            name='plants',
        ),
        migrations.AddField(
            model_name='image',
            name='flower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.Flower'),
        ),
        migrations.AddField(
            model_name='image',
            name='fruit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.Fruit'),
        ),
        migrations.AddField(
            model_name='image',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.Plant'),
        ),
        migrations.AddField(
            model_name='user',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Session'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='flower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='main.Flower'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='fruit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='main.Fruit'),
        ),
        migrations.AlterField(
            model_name='session',
            name='last_operation',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AddField(
            model_name='plantspot',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_spots', to='main.Plant'),
        ),
        migrations.AddField(
            model_name='area',
            name='ground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='main.Ground'),
        ),
    ]
