# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170309_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='climate',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='plant',
            name='form',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='plant',
            name='growth_rate',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='plant',
            name='habit',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
