# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170314_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='landscapes',
            field=models.ManyToManyField(null=True, related_name='plants', to='main.LandscapeUse'),
        ),
        migrations.AlterField(
            model_name='landscapeuse',
            name='landscape',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
