# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20170314_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False, unique=True)),
                ('form', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='form',
        ),
    ]
