# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20170314_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='forms',
            field=models.ManyToManyField(null=True, related_name='plants', to='main.Form'),
        ),
    ]
