# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_plant_forms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False, unique=True)),
                ('water', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='water',
        ),
        migrations.AddField(
            model_name='plant',
            name='waters',
            field=models.ManyToManyField(null=True, related_name='plants', to='main.Water'),
        ),
    ]
