# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20170314_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='exposure',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='landscapeuse',
            name='landscape',
            field=models.PositiveSmallIntegerField(choices=[(0, 'All'), (1, 'Accent plant'), (2, 'Alpine'), (3, 'Aquatic - ponds'), (4, 'Attract beneficial insects'), (5, 'Attract birds'), (6, 'Attract butterflies'), (7, 'Bedding plant'), (8, 'Container planting'), (9, 'Cut flower or foliage'), (10, 'Dried flower or fruit'), (11, 'Dryland'), (12, 'Erosion control'), (13, 'Espalier'), (14, 'Fall interest'), (15, 'Filler'), (16, 'Floristry'), (17, 'Forestry'), (18, 'Fragrance'), (19, 'Golf green'), (20, 'Green roof technology'), (21, 'Green walls'), (22, 'Ground cover'), (23, 'Group or mass planting'), (24, 'Hanging basket'), (25, 'Hedge row'), (26, 'Herb'), (27, 'Indoor plant'), (28, 'Lawn - sports field'), (29, 'Medicinal plant'), (30, 'Mixed shrub border'), (31, 'Native planting'), (32, 'Perennial border'), (33, 'Reclamation'), (34, 'Rock garden'), (35, 'Screening'), (36, 'Security/barrier'), (37, 'Shade tree'), (38, 'Sheared hedge'), (39, 'Small garden/space'), (40, 'Specimen plant'), (41, 'Spring interest'), (42, 'Street'), (43, 'Summer interest'), (44, 'Tall background'), (45, 'Topiary'), (46, 'Urban agriculture'), (47, 'Waterside planting'), (48, 'Wetland - bogs'), (49, 'Wild flower garden'), (50, 'Wildlife food'), (51, 'Wind break'), (52, 'Winter interest'), (53, 'Woodland margin'), (54, 'unknown'), (55, 'Arbors or trellis')]),
        ),
    ]
