# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20170314_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='forms',
            field=models.ManyToManyField(related_name='plants', to='main.Form'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='habits',
            field=models.ManyToManyField(related_name='plants', to='main.Habit'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='landscapes',
            field=models.ManyToManyField(related_name='plants', to='main.LandscapeUse'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='waters',
            field=models.ManyToManyField(related_name='plants', to='main.Water'),
        ),
    ]
