# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20170314_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ground',
            name='name',
        ),
        migrations.AddField(
            model_name='plant',
            name='exposures',
            field=models.ManyToManyField(related_name='plants', to='main.Exposure'),
        ),
        migrations.AddField(
            model_name='plant',
            name='grounds',
            field=models.ManyToManyField(related_name='plants', to='main.Ground'),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='exposure',
            field=models.PositiveSmallIntegerField(choices=[(0, 'moderate'), (1, 'Filtered shade'), (2, 'Full sun'), (3, 'Part sun/part shade'), (4, 'Full sun only if soil kept moist'), (5, 'Deep shade'), (6, 'Sheltered')]),
        ),
        migrations.AlterField(
            model_name='form',
            name='form',
            field=models.PositiveSmallIntegerField(choices=[(0, 'all'), (1, 'climbing'), (2, 'columnar'), (3, 'creeping / mat-like'), (4, 'irregular'), (5, 'mounded'), (6, 'oval - horizontal'), (7, 'oval - vertical'), (8, 'pyramidal - narrowly'), (9, 'pyramidal - widely'), (10, 'round'), (11, 'vase'), (12, 'weeping'), (13, 'unknown')]),
        ),
        migrations.AlterField(
            model_name='ground',
            name='ph',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ground',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'all'), (1, 'acidic'), (2, 'bog'), (3, 'well-drained'), (4, 'humus rich'), (5, 'alkaline'), (6, 'rocky or gravelly or dry')]),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit',
            field=models.PositiveSmallIntegerField(choices=[(0, 'all'), (1, 'arching'), (2, 'dense'), (3, 'epiphytic'), (4, 'fastigiate'), (5, 'horizontal'), (6, 'irregular'), (7, 'open'), (8, 'pendulous'), (9, 'spreading'), (10, 'stiffly upright'), (11, 'twiggy'), (12, 'upright'), (13, 'unknown')]),
        ),
        migrations.AlterField(
            model_name='water',
            name='water',
            field=models.PositiveSmallIntegerField(choices=[(0, 'low'), (1, 'moderate'), (2, 'high'), (3, 'wetlands'), (4, 'summer dry'), (5, 'aquatic'), (6, 'winter dry'), (7, 'dryland'), (8, 'unknown')]),
        ),
    ]
