# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20170315_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ground',
            name='ph',
        ),
    ]
