# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_ground_ph'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plantation_time',
            field=models.ManyToManyField(related_name='plants', to='main.Month'),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='exposure',
            field=models.PositiveSmallIntegerField(choices=[(0, 'moderate'), (1, 'filtered shade'), (2, 'full sun'), (3, 'part sun/part shade'), (4, 'full sun only if soil kept moist'), (5, 'deep shade'), (6, 'sheltered'), (7, 'unknown')]),
        ),
    ]
