# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20170317_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='colour',
            field=models.PositiveSmallIntegerField(choices=[(0, 'brown'), (1, 'unknown')]),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'capsule'), (1, 'unknown')]),
        ),
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(0, 'january'), (1, 'february'), (2, 'march'), (3, 'april'), (4, 'may'), (5, 'june'), (6, 'july'), (7, 'august'), (8, 'septembre'), (9, 'octobre'), (10, 'novembre'), (11, 'decembre')]),
        ),
    ]
