# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20170319_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='colour',
            field=models.PositiveSmallIntegerField(choices=[(0, 'brown'), (1, 'brown, purple'), (2, 'pink, brown, purple'), (3, 'green'), (4, 'violet, blue'), (5, 'unknown')]),
        ),
    ]
