# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20170319_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'capsule'), (1, 'cone (winged seeds)'), (2, 'aborted (hybrids) or absent'), (3, 'schizocarp, capsule'), (4, 'unknown')]),
        ),
    ]
