# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20170319_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False, unique=True)),
                ('colour', models.PositiveSmallIntegerField(choices=[(0, 'all'), (1, 'white'), (2, 'orange'), (3, 'yellow'), (4, 'green-yellow'), (5, 'green'), (6, 'blue'), (7, 'violet'), (8, 'purple'), (9, 'pink'), (10, 'magenta'), (11, 'red'), (12, 'dark-red'), (13, 'brown'), (14, 'bronze'), (15, 'silver'), (16, 'black'), (17, 'unknown')], null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='flower',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='fruit',
            name='colour',
        ),
        migrations.AlterField(
            model_name='flower',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='flower',
            name='colours',
            field=models.ManyToManyField(related_name='flowers', to='main.Colour'),
        ),
        migrations.AddField(
            model_name='fruit',
            name='colours',
            field=models.ManyToManyField(related_name='fruits', to='main.Colour'),
        ),
    ]
