# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20170320_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='type',
        ),
    ]
