# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_fruit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='id',
            field=models.CharField(max_length=90, primary_key=True, serialize=False, unique=True),
        ),
    ]
