# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20170322_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
