# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20170322_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='id',
            field=models.CharField(max_length=90, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='fruittype',
            name='id',
            field=models.CharField(max_length=90, primary_key=True, serialize=False, unique=True),
        ),
    ]
