# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20170322_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scent',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False, unique=True)),
                ('scent', models.PositiveSmallIntegerField(choices=[(0, 'all'), (1, 'white'), (2, 'orange'), (3, 'yellow'), (4, 'green-yellow'), (5, 'green'), (6, 'blue'), (7, 'violet'), (8, 'purple'), (9, 'pink'), (10, 'magenta'), (11, 'red'), (12, 'dark-red'), (13, 'brown'), (14, 'bronze'), (15, 'silver'), (16, 'black'), (17, 'unknown')], null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='flower',
            old_name='colours',
            new_name='petal_colours',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='scent',
        ),
        migrations.AlterField(
            model_name='flower',
            name='months',
            field=models.ManyToManyField(related_name='flowers', to='main.Month'),
        ),
        migrations.AlterField(
            model_name='fruittype',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'All'), (1, 'Aggregate fruit'), (2, 'Achene'), (3, 'Berry'), (4, 'Capsule'), (5, 'Cypsela'), (6, 'Drupe'), (7, 'Edible'), (8, 'Follicle'), (9, 'Grain'), (10, 'Hesperidium'), (11, 'Legume'), (12, 'Multiple fruit'), (13, 'Nut'), (14, 'Pepo'), (15, 'Pome'), (16, 'Samara'), (17, 'Schizocarp'), (18, 'Silicle'), (19, 'Silique'), (20, 'Aborted or absent'), (21, 'Cone'), (22, 'Sporangium'), (23, 'unknown')]),
        ),
        migrations.AddField(
            model_name='flower',
            name='scents',
            field=models.ManyToManyField(related_name='flowers', to='main.Scent'),
        ),
    ]
