# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20170322_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='colour',
            field=models.PositiveSmallIntegerField(choices=[(0, 'all'), (1, 'white'), (2, 'orange'), (3, 'yellow'), (4, 'green-yellow'), (5, 'green'), (6, 'blue'), (7, 'violet'), (8, 'purple'), (9, 'pink'), (10, 'magenta'), (11, 'red'), (12, 'dark-red'), (13, 'brown'), (14, 'bronze'), (15, 'silver'), (16, 'black'), (17, 'showy'), (18, 'unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='fruittype',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'all'), (1, 'aggregate fruit'), (2, 'achene'), (3, 'berry'), (4, 'capsule'), (5, 'cypsela'), (6, 'drupe'), (7, 'edible'), (8, 'follicle'), (9, 'grain'), (10, 'hesperidium'), (11, 'legume'), (12, 'multiple fruit'), (13, 'nut'), (14, 'pepo'), (15, 'pome'), (16, 'samara'), (17, 'schizocarp'), (18, 'silicle'), (19, 'silique'), (20, 'aborted or absent'), (21, 'cone'), (22, 'sporangium'), (23, 'unknown')]),
        ),
        migrations.AlterField(
            model_name='scent',
            name='scent',
            field=models.PositiveSmallIntegerField(choices=[(0, 'none'), (1, 'fragrant'), (2, 'spicy'), (3, 'sweet'), (4, 'lemony'), (5, 'unknown')], null=True),
        ),
    ]
