# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20170322_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='colour',
            field=models.PositiveSmallIntegerField(choices=[(0, 'all'), (1, 'white'), (2, 'orange'), (3, 'yellow'), (4, 'green-yellow'), (5, 'green'), (6, 'blue'), (7, 'violet'), (8, 'purple'), (9, 'pink'), (10, 'magenta'), (11, 'red'), (12, 'dark-red'), (13, 'brown'), (14, 'bronze'), (15, 'silver'), (16, 'black'), (17, 'showy'), (18, 'not showy'), (19, 'none'), (20, 'unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='scent',
            name='scent',
            field=models.PositiveSmallIntegerField(choices=[(0, 'none'), (1, 'fragrant'), (2, 'spicy'), (3, 'sweet'), (4, 'lemony'), (5, 'musky'), (6, 'unknown')], null=True),
        ),
    ]
