# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20170322_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scent',
            name='scent',
            field=models.PositiveSmallIntegerField(choices=[(0, 'none'), (1, 'fragrant'), (2, 'spicy'), (3, 'sweet'), (4, 'lemony'), (5, 'musky'), (6, 'unpleasant'), (7, 'unknown')], null=True),
        ),
    ]
