# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20170322_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='can_flower',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='can_fruit',
        ),
    ]
