# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20170322_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
