# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20170409_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.BinaryField(max_length=90, null=True),
        ),
    ]
