# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20170424_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='main.Project'),
        ),
    ]
